// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvn0XtZArV_ECRkOWOgVIvdacHcbCP9I',
    appId: '1:207161186689:web:b31d16f2c6197d98257080',
    messagingSenderId: '207161186689',
    projectId: 'humequity-idp',
    authDomain: 'humequity-idp.firebaseapp.com',
    storageBucket: 'humequity-idp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dbFj2ZbG_5WCeiBOh8jS5g7oQMZd5nM',
    appId: '1:207161186689:android:97a4b07cfcd38b3c257080',
    messagingSenderId: '207161186689',
    projectId: 'humequity-idp',
    storageBucket: 'humequity-idp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJd2O-Ek_Fu9ADstrNTLMP_pLSDc8re2s',
    appId: '1:207161186689:ios:0c9206109f6575a8257080',
    messagingSenderId: '207161186689',
    projectId: 'humequity-idp',
    storageBucket: 'humequity-idp.firebasestorage.app',
    iosBundleId: 'com.technicate.skillroot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJd2O-Ek_Fu9ADstrNTLMP_pLSDc8re2s',
    appId: '1:207161186689:ios:0c9206109f6575a8257080',
    messagingSenderId: '207161186689',
    projectId: 'humequity-idp',
    storageBucket: 'humequity-idp.firebasestorage.app',
    iosBundleId: 'com.technicate.skillroot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvn0XtZArV_ECRkOWOgVIvdacHcbCP9I',
    appId: '1:207161186689:web:1fd812603e4b6c5a257080',
    messagingSenderId: '207161186689',
    projectId: 'humequity-idp',
    authDomain: 'humequity-idp.firebaseapp.com',
    storageBucket: 'humequity-idp.firebasestorage.app',
  );

}